from datetime import datetime

MOCK_FLATS = [
    {
        "cian_id": "012345678",
        "url": "https://www.cian.ru/sale/flat/012345678/",
        "address": "Москва, Мещанский район, ул. Проспект Мира, д. 19",
        "price_rub": 10200000,
        "total_area": 39.0,
        "rooms": 1,
        "floor": 8,
        "floors_total": 16,
        "build_year": 2016,
        "material": "монолит",
        "repair_state": "хорошее",
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
    },
    {
        "cian_id": "087654321",
        "url": "https://www.cian.ru/sale/flat/087654321/",
        "address": "Москва, Басманный район, ул. Красные Ворота, д. 5",
        "price_rub": 12500000,
        "total_area": 45.5,
        "rooms": 1,
        "floor": 3,
        "floors_total": 12,
        "build_year": 2010,
        "material": "кирпич",
        "repair_state": "евроремонт",
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
    },
    {
        "cian_id": "111222333",
        "url": "https://www.cian.ru/sale/flat/111222333/",
        "address": "Москва, Тверской район, ул. Тверская, д. 7",
        "price_rub": 9800000,
        "total_area": 36.0,
        "rooms": 1,
        "floor": 5,
        "floors_total": 9,
        "build_year": 1995,
        "material": "панель",
        "repair_state": "под ремонт",
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
    },
]
